# Generated by Django 3.1.3 on 2023-09-17 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_activated', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('role', models.CharField(default='user', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VariantCaterings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=255)),
                ('extra_price', models.IntegerField()),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_variants', to='api.catering')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered_at', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=255)),
                ('catering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering', to='api.catering')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='api.user')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='api.variantcaterings')),
            ],
        ),
        migrations.AddField(
            model_name='catering',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caterings', to='api.user'),
        ),
    ]
